global: # 全局配置
  scrape_interval: 10s        # 抓取时间间隔
  scrape_timeout: 10s          # 抓取超时时间
  evaluation_interval: 10s    # 规则评估(计算)间隔

# 抓取配置:
scrape_configs:
  - job_name: "prometheus_server"
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ["127.0.0.1:9090"]
       # label 配置，作用域当前静态配置下的所有被抓取的指标
        labels:
          app: "prometheus"
