global: # 全局配置
  scrape_interval: 10s        # 抓取时间间隔
  scrape_timeout: 10s          # 抓取超时时间
  evaluation_interval: 10s    # 规则评估(计算)间隔

# 抓取配置:
scrape_configs:
  - job_name: "prometheus_server"
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ["127.0.0.1:9090"]
        # label 配置，作用域当前静态配置下的所有被抓取的指标
        labels:
          app: "prometheus"
  - job_name: "metrics-generator"
    static_configs:
      - targets: ["localhost:8788"]
        labels:
          app: "metrics-generator"

  - job_name: "sandbox_lb"
    scheme: 'http'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["10.221.49.156:8790"]
        labels:
          app: sandbox_lb
